name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Unit tests
        run: pnpm test:unit

      - name: End-to-end tests
        run: pnpm test:e2e
        env:
          NEXTAUTH_SECRET: test

      - name: Build
        run: pnpm build
        env:
          NEXT_PUBLIC_SITE_URL: https://karting-evasion.example
          NEXTAUTH_SECRET: test
